CAM-13912: migrate examples: DMN, Spin, Multi-Tenancy, Migration
camunda/camunda-bpm-examples pull request #145
Opened 2021-09-23 08:59 UTC by ThorbenLindhauer

related to CAM-13912

2021-09-23 08:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/camunda/camunda-bpm-examples?pullRequest=145) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/camunda/camunda-bpm-examples?pullRequest=145) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/camunda/camunda-bpm-examples?pullRequest=145) it.</sub>

2021-09-23 12:05 UTC, mboskamp requested changes
Found a small typo. Otherwise it looks good :)

2021-09-23 15:24 UTC, ThorbenLindhauer commented on multi-tenancy/tenant-identifier-shared/README.md
> +4. Deploy it to a share process engine distribution of your own choice (Tomcat, Wildfly, Weblogic, Websphere - this example does not work with Camunda Platform Run)
Thanks, should be fixed now.

2021-09-24 07:39 UTC, mboskamp approved these changes

2021-09-24 11:03 UTC, merged